> import Prelude hiding (pred)

Currently, the interpreter uses an outermost reduction strategy. We can adapt the `reduce` function to implement an innermost reduction strategy (see InterpretInnermost.hs).

It is important that a substitition only happens on a given term, if there are not substitutions possible within that term or on a different more nested term. Anything else remains unchanged, that is, we make one step at a time and recude the left part of an application first.

Now we can use this module for the task at hand.

> import Exercises.Exercise4.Interpreter
> import Exercises.Exercise4.InterpreterInnermost

We're reusing the functionality of the given interpreter to define `fac`.

> fac = f :->: x :->: (cond :@: (isNull :@: Var x) :@: nat 1 :@: (mul :@: Var x :@: (Var f :@: (pred :@: Var x))))
>
> isNull = 'n' :->: (Var 'n' :@: (x :->: false)) :@: true
>
> mul = 'm' :->: 'n' :->: 'a' :->: Var 'm' :@: (Var 'n' :@: Var 'a')
>
> pred = 'n' :->: 'f' :->: 'x' :->: Var 'n' :@: ('g' :->: 'h' :->: Var 'h' :@: (Var 'g' :@: Var 'f')) :@: ('u' :->: Var 'x') :@: ('u' :->: Var 'u')

Let's start by using the outermost strategy.

    *OutermostInnermost> eval $ fix :@: fac :@: nat 1
    \a.\x.a x

<!--
    *OutermostInnermost> printSteps $ fix :@: fak :@: nat 1
    (\f.(\x.f (x x)) (\x.f (x x))) (\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (\f.\x.f x)
    (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\f.\x.f x)
    (\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x))) (\f.\x.f x)
    (\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (\f.\x.f x)
    (\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) (\f.\x.f x)) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\x.\y.(\n.n (\x.\x.\y.y) (\x.\y.x)) (\f.\x.f x) x y) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\y.(\n.n (\x.\x.\y.y) (\x.\y.x)) (\f.\x.f x) (\f.\x.f x) y) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\n.n (\x.\x.\y.y) (\x.\y.x)) (\f.\x.f x) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\f.\x.f x) (\x.\x.\y.y) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\x.(\x.\x.\y.y) x) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\x.\x.\y.y) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\x.\y.y) (\f.\x.f x) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\y.y) ((\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))
    (\m.\n.\a.m (n a)) (\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)))
    (\n.\a.(\f.\x.f x) (n a)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)))
    \a.(\f.\x.f x) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) a)
    \a.\x.(\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) a x
    \a.\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x))) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) a x
    \a.\x.(\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) a x
    \a.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\x.\y.(\n.n (\x.\x.\y.y) (\x.\y.x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) x y) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\y.(\n.n (\x.\x.\y.y) (\x.\y.x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) (\f.\x.f x) y) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\n.n (\x.\x.\y.y) (\x.\y.x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x) (\x.\x.\y.y) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\f.\x.(\f.\x.f x) (\g.\h.h (g f)) (\u.x) (\u.u)) (\x.\x.\y.y) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\x.(\f.\x.f x) (\g.\h.h (g (\x.\x.\y.y))) (\u.x) (\u.u)) (\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\f.\x.f x) (\g.\h.h (g (\x.\x.\y.y))) (\u.\x.\y.x) (\u.u) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\x.(\g.\h.h (g (\x.\x.\y.y))) x) (\u.\x.\y.x) (\u.u) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\g.\h.h (g (\x.\x.\y.y))) (\u.\x.\y.x) (\u.u) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\h.h ((\u.\x.\y.x) (\x.\x.\y.y))) (\u.u) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\u.u) ((\u.\x.\y.x) (\x.\x.\y.y)) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\u.\x.\y.x) (\x.\x.\y.y) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\x.\y.x) (\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\y.\f.\x.f x) ((\m.\n.\a.m (n a)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x)) ((\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) (\x.(\f.\x.(\f.\x.\y.f x y) ((\n.n (\x.\x.\y.y) (\x.\y.x)) x) (\f.\x.f x) ((\m.\n.\a.m (n a)) x (f ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) x)))) (x x)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) ((\n.\f.\x.n (\g.\h.h (g f)) (\u.x) (\u.u)) (\f.\x.f x))))) a x
    \a.\x.(\f.\x.f x) a x
    \a.\x.(\x.a x) x
    \a.\x.a x
-->

Next up, we try to evaluate the term using the innermost strategy.

    *OutermostInnermost> evalIM $ fix :@: fac :@: nat 1
    ^CInterrupted.
    
Unfortunately, there are no computations to observe and we enventually need to stop the computation.
When we only compute 50 reduction steps, we can at least take a look at the term so far. The term is pretty hard to parse, however, we can see some repetitions that eventually are a good indicator for the non-terminating computation that is happening here using innermost.

    (evalSeqIM $ fix :@: fak :@: nat 1) !! 50
    (\f.\x.x (\a.\a.\y.y) (\a.\y.a) (\a.\b.a b) (\a.x (f (\f.\a.x (\g.\h.h (g f)) (\u.a) (\u.u)) a))) (\a.a (\b.\b.\y.y) (\b.\y.b) (\b.\c.b c) (\b.a (a (\g.\h.h (g (\b.\b.\y.y))) (\u.\b.\y.b) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g f)) (\u.b) (\u.u)) (a (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))) (\u.\u.\b.\y.b) (\u.u) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g f)))) (\u.\u.b) (\u.u) (\u.u)) (a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))))) (\u.\u.\u.\b.\y.b) (\u.u) (\u.u) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))) (\u.\u.\u.b) (\u.u) (\u.u) (\u.u)) (a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))))))) (\u.\u.\u.\u.\b.\y.b) (\u.u) (\u.u) (\u.u) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))))) (\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u)) (a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))))))))) (\u.\u.\u.\u.\u.\b.\y.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))))))) (\u.\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u)) (a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))))))))))) (\u.\u.\u.\u.\u.\u.\b.\y.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))))))))) (\u.\u.\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u)) ((\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\b.\b.\y.y))))))))))))))) (\u.\u.\u.\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u)) (\b.\y.b) (\b.\c.b c) (\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))))))))))) (\u.\u.\u.\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u)) ((\x.\a.a (\b.\b.\y.y) (\b.\y.b) (\b.\c.b c) (\b.a (x x (\f.\b.a (\g.\h.h (g f)) (\u.b) (\u.u)) b))) (\x.\a.a (\b.\b.\y.y) (\b.\y.b) (\b.\c.b c) (\b.a (x x (\f.\b.a (\g.\h.h (g f)) (\u.b) (\u.u)) b))) (\f.\b.(\f.\b.a (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g (\g.\h.h (g f)))))))))))))) (\u.\u.\u.\u.\u.\u.\u.b) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u) (\u.u)) (\g.\h.h (g f)) (\u.b) (\u.u)) b)) b)) b)) b)) b)) b)) b)) b))) (\f.\x.f x)
